CREATE DATABASE IF NOT EXISTS comparus CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'admin'@'%' IDENTIFIED BY 'admin123';
GRANT ALL PRIVILEGES ON comparus.* TO 'admin'@'%';
FLUSH PRIVILEGES;